FROM centos:centos7

ENV CODE_BASE_DIR="/code"
ENV APP_NAME="ooo_rms_orderservice"
ENV SERVICE_NAME="orderservice"

USER root

RUN yum update -y && \
    yum install -y git && \
    yum groupinstall -y 'Development Tools' &&\
    yum install -y centos-release-scl && \
     yum install -y gcc openssl-devel bzip2-devel libffi-devel zlib-devel &&\
    yum install -y epel-release && \
    yum install -y llvm5.0-devel &&\
    yum install -y postgresql-devel && \
    yum install -y python3-devel && \
    yum install -y gcc && \
    yum install -y jq && \
    yum install -y python3-pip

RUN mkdir -p "${CODE_BASE_DIR}"/"${APP_NAME}"

ADD orderservice "${CODE_BASE_DIR}"/"${APP_NAME}"/orderservice/
RUN cd "${CODE_BASE_DIR}"/"${APP_NAME}"/ && \
    pwd && \
    python3 -m venv venv 

COPY  orderservice/requirements.txt "${CODE_BASE_DIR}"/"${APP_NAME}"/"${SERVICE_NAME}"/
COPY  orderservice/app.py "${CODE_BASE_DIR}"/"${APP_NAME}"/"${SERVICE_NAME}"/
COPY  orderservice/helpers.py "${CODE_BASE_DIR}"/"${APP_NAME}"/"${SERVICE_NAME}"/
COPY  orderservice/entrypoint.sh "${CODE_BASE_DIR}"/"${APP_NAME}"/"${SERVICE_NAME}"/
COPY  orderservice/models.py "${CODE_BASE_DIR}"/"${APP_NAME}"/"${SERVICE_NAME}"/


RUN ls -al /code/ooo_rms_orderservice/orderservice

RUN cd "${CODE_BASE_DIR}"/"${APP_NAME}"/"${SERVICE_NAME}"/ &&\
    pip3 install --upgrade pip && \
    pip3 install -r requirements.txt 

ENTRYPOINT ["/bin/bash","/code/ooo_rms_orderservice/orderservice/entrypoint.sh"]


