class JSONKeys:
    ItemId = "Item_id"
    ItemDescription = "Item_description"
    ItemName = "Item_name"
    ItemPrice = "Item_price"
    ItemRestaurntId = "Item_restaurant_id"
    ItemCategoryId ="Item_category_id"
    ItemImageLink = "Item_image_link"
    ItemStockQuantity = "Item_Stock_Quantity"
    RestaurantName = "Restaurant_name"
    RestaurantImageURL = "Restaurant_image_url"
    CategoryName= "category_name"
    ItemIdParam= "itemId"
    ItemNameParam= "itemName"  
    RestaurantIdParam = "restaurantId"